# Generated by Django 4.2.19 on 2025-02-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rec'),
    ]

    operations = [
        migrations.AddField(
            model_name='rec',
            name='url',
            field=models.URLField(blank=True, max_length=42, null=True),
        ),
    ]
