# Generated by Django 4.2.19 on 2025-02-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_rec_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rec',
            name='url',
            field=models.URLField(max_length=42),
        ),
    ]
