# Generated by Django 4.2.19 on 2025-02-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_rec_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rec',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
