# Generated by Django 4.2.19 on 2025-02-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_rec_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
